version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Toronto
  open-pull-requests-limit: 10
  
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    timezone: America/Toronto
